namespace Edu100.Enum
{
	/// <summary>
	/// 客户端ui深度类型分类
	/// auto generated by T4
	/// </summary>
	public enum ClientUIDepthTypeID
	{
	
		/// <summary>
		/// 客户端UI
		/// </summary>
		ClientDefault = 1,
	
		/// <summary>
		/// 教学UI
		/// </summary>
		TeachDefault = 2,
	
		/// <summary>
		/// 游戏默认层次
		/// </summary>
		GameDefault = 3,
	
		/// <summary>
		/// 游戏中层
		/// </summary>
		GameMid = 4,
	
		/// <summary>
		/// 游戏常驻层
		/// </summary>
		GameConstant = 5,
	
		/// <summary>
		/// 游戏高层次
		/// </summary>
		GameTop = 6,
	
		/// <summary>
		/// 游戏最顶层
		/// </summary>
		GameMaxTop = 7,
	
		/// <summary>
		/// 教学弹出层
		/// </summary>
		TeachPop = 8,
	
		/// <summary>
		/// 客户端弹出层
		/// </summary>
		ClientPop = 9,
	
		/// <summary>
		/// Fps信息
		/// </summary>
		Fps = 10,
	
		/// <summary>
		/// 教学端Loading层
		/// </summary>
		TeachLoading = 11,
	
		/// <summary>
		/// 全屏Loading层
		/// </summary>
		ClientLoading = 12,
	
		/// <summary>
		/// 客户端弹出层(适用于学生端和教师端的共有UII)
		/// </summary>
		ClientPop2048 = 13,
	
		/// <summary>
		/// 教师端的H5页面显示层
		/// </summary>
		TeachH5Web = 14,
	
		/// <summary>
		/// 游戏特殊层，用于屏幕适配，部分需要放缩的Panel
		/// </summary>
		GameSpecial = 15,
	
		/// <summary>
		/// 学生端特殊层，以16:9进行适配。小于16:9，以宽度适配，反之以高适配
		/// </summary>
		CanvasTeachPop1609 = 16,
	
	}
}
