namespace Edu100.Enum
{
	/// <summary>
	/// 系统分类讨论
	/// auto generated by T4
	/// </summary>
	public enum ClientUITypeID
	{
	
		/// <summary>
		/// 系统级
		/// </summary>
		System = 1,
	
		/// <summary>
		/// 系统子界面
		/// </summary>
		SubSystem = 2,
	
		/// <summary>
		/// 辅助系统
		/// </summary>
		HelperSystem = 3,
	
		/// <summary>
		/// 弹框提示类
		/// </summary>
		Alert = 4,
	
		/// <summary>
		/// 主界面级别
		/// </summary>
		mainwindow = 5,
	
	}
}
