namespace Edu100.Enum
{
	/// <summary>
	/// 客户端UI资源配置表
	/// auto generated by T4
	/// </summary>
	public enum PanelID
	{
	
		/// <summary>
		/// 初始化
		/// </summary>
		PREFABE_ID_INVAILD = 0,
	
		/// <summary>
		/// 加载面板
		/// </summary>
		Loading = 1,
	
		/// <summary>
		/// 上课界面
		/// </summary>
		Teach = 2,
	
		/// <summary>
		/// 激励奖励界面
		/// </summary>
		Reward = 3,
	
		/// <summary>
		/// 语音识别UI界面
		/// </summary>
		MainUI = 4,
	
		/// <summary>
		/// 老师端登录界面
		/// </summary>
		LoginUI = 5,
	
		/// <summary>
		/// 学生端主界面
		/// </summary>
		HomePageMobile = 6,
	
		/// <summary>
		/// 老师端主界面
		/// </summary>
		HomePagePcTab = 7,
	
		/// <summary>
		/// 权限页面手机端
		/// </summary>
		AuthUIMobile = 9,
	
		/// <summary>
		/// 手机端主页背景
		/// </summary>
		HomePageMobileBack = 10,
	
		/// <summary>
		/// 客户端播放视频
		/// </summary>
		ClientVideoPlay = 11,
	
		/// <summary>
		/// 教师端课程表页
		/// </summary>
		SchedulePc = 12,
	
		/// <summary>
		/// 手机端提示框
		/// </summary>
		MobileToast = 13,
	
		/// <summary>
		/// 手机端loading画面
		/// </summary>
		MobileLoading = 14,
	
		/// <summary>
		/// 解说者模式
		/// </summary>
		ExplainModule = 15,
	
		/// <summary>
		/// 测试课程
		/// </summary>
		TestLessonSetting = 17,
	
		/// <summary>
		/// 场景切换渐变动画
		/// </summary>
		SceneFade = 18,
	
		/// <summary>
		/// 教学窗口加载面板
		/// </summary>
		TeachLoading = 19,
	
		/// <summary>
		/// 建造游戏界面
		/// </summary>
		BuildGame = 75,
	
		/// <summary>
		/// 跟读接龙模板（动词/动词）界面
		/// </summary>
		Chain = 76,
	
		/// <summary>
		/// 内容总结界面
		/// </summary>
		ContentSummaryUI = 78,
	
		/// <summary>
		/// 拼装游戏界面
		/// </summary>
		AssembleGame = 80,
	
		/// <summary>
		/// 左下角小窗
		/// </summary>
		LeftBottomBorder = 81,
	
		/// <summary>
		/// 预习环节句式输入卡片界面
		/// </summary>
		PreviewSentenceInput = 82,
	
		/// <summary>
		/// 字母卡片引出输入模板-字母冒险界面
		/// </summary>
		CharAdventure = 83,
	
		/// <summary>
		/// 特写遮罩界面
		/// </summary>
		CloseUpMask = 85,
	
		/// <summary>
		/// 听音识意侦测（类型2:UI弹窗侦测）
		/// </summary>
		Detection = 86,
	
		/// <summary>
		/// 学生端左下角点击提示界面
		/// </summary>
		StudentControlUI = 90,
	
		/// <summary>
		/// 通用学生右下角视频框和Tom框
		/// </summary>
		StudentBorderUI = 91,
	
		/// <summary>
		/// 通用特写UI
		/// </summary>
		CommonCloseUpUI = 92,
	
		/// <summary>
		/// 摄像机截图（拍照效果）
		/// </summary>
		ScreenShot = 93,
	
		/// <summary>
		/// 贴图游戏
		/// </summary>
		Paste = 123,
	
		/// <summary>
		/// 联想气泡界面
		/// </summary>
		AssociationBubble = 148,
	
		/// <summary>
		/// 环节结算卡片界面
		/// </summary>
		SummaryCard = 149,
	
		/// <summary>
		/// 触发角色做指定得动作
		/// </summary>
		TriggerAction = 337,
	
		/// <summary>
		/// 通用卡片
		/// </summary>
		CommonCard = 340,
	
		/// <summary>
		/// 语音控制角色做指定动作
		/// </summary>
		SpeechDoAction = 342,
	
		/// <summary>
		/// 课中1v1教学，颜色显示面板Lv1
		/// </summary>
		ColorPanelLv1 = 345,
	
		/// <summary>
		/// 课中1v1教学，特征教学显示面板Lv1
		/// </summary>
		FeaturePanelLv1 = 346,
	
		/// <summary>
		/// 收集游戏
		/// </summary>
		CollectionGame = 347,
	
		/// <summary>
		/// 动词教学能量条
		/// </summary>
		EnergyBar = 348,
	
		/// <summary>
		/// Tom颜色教学弹力气泡
		/// </summary>
		BounceBubble = 349,
	
		/// <summary>
		/// 名词制作食物材料框
		/// </summary>
		MakeFoodMaterialBox = 350,
	
		/// <summary>
		/// 通用特写UI
		/// </summary>
		Panel_UICloseUp = 445,
	
		/// <summary>
		/// 气泡相关界面
		/// </summary>
		Panel_Bubble = 667,
	
		/// <summary>
		/// 教师端老师评分选择
		/// </summary>
		TeacherGiveStars = 668,
	
		/// <summary>
		/// 跑酷跟读角色选择界面
		/// </summary>
		ParkourListenPanel = 670,
	
		/// <summary>
		/// 串场进度条
		/// </summary>
		StageFieldProcess = 671,
	
		/// <summary>
		/// 手机端登录界面
		/// </summary>
		LoginMobileUI = 100000,
	
		/// <summary>
		/// 自然拼读-组单词环节UI
		/// </summary>
		WordCombinationCard = 100003,
	
		/// <summary>
		/// Chant 新版本
		/// </summary>
		ChantTeaching = 100004,
	
		/// <summary>
		/// 通用Carrie模块
		/// </summary>
		CommonCarrie = 100007,
	
		/// <summary>
		/// 检测点-看图发音
		/// </summary>
		CheckLookAndAudio = 100008,
	
		/// <summary>
		/// 综合Chant
		/// </summary>
		IntegrationChant = 100012,
	
		/// <summary>
		/// 评测
		/// </summary>
		Evaluating = 100013,
	
		/// <summary>
		/// Torch
		/// </summary>
		Torch = 100015,
	
		/// <summary>
		/// 放置-动词
		/// </summary>
		PlaceVerb = 100016,
	
		/// <summary>
		/// 通用右侧句式卡片UI
		/// </summary>
		CommonNounSentenceCardRight = 100022,
	
		/// <summary>
		/// 通用Carrie提示模块
		/// </summary>
		CommonCarrieTips = 100023,
	
		/// <summary>
		/// 分享模块点击UI分享
		/// </summary>
		Panel_Iteams_action = 100025,
	
		/// <summary>
		/// 句式教学
		/// </summary>
		WSentenceTeaching = 100027,
	
		/// <summary>
		/// 句式练习V2界面
		/// </summary>
		SentencePracticeV2 = 100028,
	
		/// <summary>
		/// 指令点击 显示道具列表
		/// </summary>
		CommandItemList = 100030,
	
		/// <summary>
		/// 看图发音照相机UI
		/// </summary>
		CameraUI = 100031,
	
		/// <summary>
		/// 指令点击 显示道具列表
		/// </summary>
		TemplateFieldPanel = 100032,
	
		/// <summary>
		/// 场景淡出淡入效果
		/// </summary>
		ScreenFadeInOut = 100033,
	
		/// <summary>
		/// 对话教学卡片
		/// </summary>
		DialogueTeachV3Card = 100035,
	
		/// <summary>
		/// 收集（卡片）底部UI栏
		/// </summary>
		CardCollect = 100036,
	
		/// <summary>
		/// 通用事件条bar
		/// </summary>
		CommandTimeBar = 100039,
	
		/// <summary>
		/// 对话教学卡片
		/// </summary>
		ColletIcon = 100040,
	
		/// <summary>
		/// 直播环节老师端跟读和侦测页显示的提示UI
		/// </summary>
		TeacherTipsUI = 100041,
	
		/// <summary>
		/// 教师端金币评分
		/// </summary>
		TeacherGiveMedalScore = 100042,
	
		/// <summary>
		/// 句式教学_相册
		/// </summary>
		PhotoCollector = 100044,
	
		/// <summary>
		/// 课前等待页面
		/// </summary>
		ClassWait = 100045,
	
		/// <summary>
		/// 通用拖拽提示UI
		/// </summary>
		CommonDragTips = 100047,
	
		/// <summary>
		/// 积分商城UI
		/// </summary>
		IntegralMall = 500047,
	
		/// <summary>
		/// 通用跑马灯解决方案
		/// </summary>
		HorseLight = 500048,
	
		/// <summary>
		/// 自适应课中串场
		/// </summary>
		AdaptiveClassCrosstalk = 500049,
	
		/// <summary>
		/// 时间到了提示用户上正课
		/// </summary>
		TimeArriveNotice = 500050,
	
		/// <summary>
		/// 学生端个人信息
		/// </summary>
		UserInfo = 500051,
	
		/// <summary>
		/// 断网提示
		/// </summary>
		BadInternet = 500052,
	
		/// <summary>
		/// 看图发音-名词专有UI
		/// </summary>
		LookAndSayNounUI = 500053,
	
		/// <summary>
		/// 放置游戏
		/// </summary>
		PlaceGame = 500054,
	
		/// <summary>
		/// 障碍跑
		/// </summary>
		ObstacleRunPanel = 500056,
	
		/// <summary>
		/// 血条
		/// </summary>
		HaemalStrand = 500058,
	
		/// <summary>
		/// 升级提示页
		/// </summary>
		UpdateInfo = 500059,
	
		/// <summary>
		/// 开礼物盒
		/// </summary>
		OpenBox = 500060,
	
		/// <summary>
		/// TomAI字母教学
		/// </summary>
		TomAILetterTeaching = 500061,
	
		/// <summary>
		/// 收集（图标）底部UI栏
		/// </summary>
		FloatCollection = 500062,
	
		/// <summary>
		/// 临时资源占位标记显示
		/// </summary>
		TemporaryResourceTags = 500065,
	
		/// <summary>
		/// 用户协议
		/// </summary>
		UserAgreement = 500066,
	
		/// <summary>
		/// 隐私条款
		/// </summary>
		UserPrivacy = 500067,
	
		/// <summary>
		/// 积分商城奖励提示框
		/// </summary>
		MallAwardWidget = 500069,
	
		/// <summary>
		/// 积分商城购买提示框
		/// </summary>
		MallBuyTipWidget = 500070,
	
		/// <summary>
		/// 礼包获得提示窗口
		/// </summary>
		GiftWidget = 500071,
	
		/// <summary>
		/// 应用升级更新界面
		/// </summary>
		AppUpdateUI = 500072,
	
		/// <summary>
		/// 设置界面
		/// </summary>
		Setting = 500073,
	
		/// <summary>
		/// 关于我们
		/// </summary>
		AboutUS = 500074,
	
		/// <summary>
		/// 检查设备
		/// </summary>
		CheckDevice = 500075,
	
		/// <summary>
		/// Tip
		/// </summary>
		Tip = 500076,
	
		/// <summary>
		/// 拖拽UI
		/// </summary>
		DragIcon = 500079,
	
		/// <summary>
		/// 登出界面
		/// </summary>
		Logout = 500080,
	
		/// <summary>
		/// 用户踢掉
		/// </summary>
		ForceQuit = 500081,
	
		/// <summary>
		/// BottomMask
		/// </summary>
		BottomMask = 500082,
	
		/// <summary>
		/// 老师端用户协议
		/// </summary>
		TeacherUserAgreement = 500084,
	
		/// <summary>
		/// 老师隐私条款
		/// </summary>
		TeacherUserPrivacy = 500085,
	
		/// <summary>
		/// 自适应阶段串场
		/// </summary>
		AdaptivePhaseJudged = 500086,
	
		/// <summary>
		/// 物品组卡片UI
		/// </summary>
		ItemGourpIcon = 500087,
	
		/// <summary>
		/// 动词组合图标UI
		/// </summary>
		VerbCombinationIcon = 500088,
	
		/// <summary>
		/// 角色物品组拍照
		/// </summary>
		ItemGourpPhotograph = 500089,
	
		/// <summary>
		/// 直播加载面板
		/// </summary>
		LiveLoading = 500090,
	
		/// <summary>
		/// 动词组合卡片UI栏
		/// </summary>
		CardContainer = 500091,
	
		/// <summary>
		/// 报障面板
		/// </summary>
		ReportBug = 500092,
	
		/// <summary>
		/// 课程大纲界面
		/// </summary>
		LessonSyllabus = 500093,
	
		/// <summary>
		/// Carrie玩法介绍界面
		/// </summary>
		GamePlay = 500094,
	
		/// <summary>
		/// 注销面板
		/// </summary>
		UnRegister = 500095,
	
		/// <summary>
		/// 网络状况提示
		/// </summary>
		NetStatus = 500096,
	
		/// <summary>
		/// 动词复习
		/// </summary>
		VerbReview = 500099,
	
		/// <summary>
		/// 动词复习
		/// </summary>
		Star = 500100,
	
		/// <summary>
		/// 动词复习
		/// </summary>
		WrongRestudy = 500101,
	
		/// <summary>
		/// 课程大纲工具界面
		/// </summary>
		LessonSyllabusHelper = 500102,
	
		/// <summary>
		/// H5页面加载
		/// </summary>
		H5WebLoading = 500103,
	
		/// <summary>
		/// 课前预习和课后歌谣
		/// </summary>
		PreLearnAndSong = 500104,
	
		/// <summary>
		/// 课前预习和课后歌谣的实例游戏中要显示的UI，会跳出游戏
		/// </summary>
		PreGamingUI = 500105,
	
		/// <summary>
		/// 登录信息补充
		/// </summary>
		InfoSupplement = 500106,
	
		/// <summary>
		/// 动词组合卡片UI栏V2
		/// </summary>
		CardLeftContainerV2 = 500107,
	
		/// <summary>
		/// 放置游戏V2.0
		/// </summary>
		PlaceGameV2 = 500108,
	
		/// <summary>
		/// 教师端断网提示
		/// </summary>
		TeacherBadInternet = 500109,
	
		/// <summary>
		/// 3D特写显示为2D图片
		/// </summary>
		Magnifier2D = 500110,
	
		/// <summary>
		/// 综合复习
		/// </summary>
		ComplexReview = 500111,
	
		/// <summary>
		/// 动词组合图标UI（录播）
		/// </summary>
		VerbCombinationIconRecordPlay = 500112,
	
		/// <summary>
		/// 动词组合图标UI 2.0
		/// </summary>
		LiveVerbCombinationIcon = 500113,
	
		/// <summary>
		/// 通用UI全屏特效（和奖励区分开）
		/// </summary>
		CommonScreenEffect = 500114,
	
		/// <summary>
		/// 班主任模板_奖励pk
		/// </summary>
		TeacherSummary = 500115,
	
		/// <summary>
		/// 荣誉墙
		/// </summary>
		HonorWall = 500116,
	
		/// <summary>
		/// 名称选择面板
		/// </summary>
		NamePick = 500117,
	
		/// <summary>
		/// 视频mp4播放模板
		/// </summary>
		TemplateVideoPlay = 500118,
	
		/// <summary>
		/// 通用道具卡片
		/// </summary>
		CommonItemCard = 500119,
	
		/// <summary>
		/// 选择面板
		/// </summary>
		Picker = 500120,
	
		/// <summary>
		/// 日期选择面板
		/// </summary>
		PickerDate = 500121,
	
		/// <summary>
		/// 自然拼读听音识意
		/// </summary>
		PhonicsListen = 500122,
	
		/// <summary>
		/// 形容词收集1
		/// </summary>
		AdjCollect1 = 500123,
	
		/// <summary>
		/// 形容词收集2
		/// </summary>
		AdjCollect2 = 500124,
	
		/// <summary>
		/// 自然拼读找东西界面
		/// </summary>
		PhonicsFindThing = 500125,
	
		/// <summary>
		/// 形容词放置UI
		/// </summary>
		AdjPlace = 500126,
	
		/// <summary>
		/// 自然拼读暴力输入模板
		/// </summary>
		PhonicsViolenceInput = 500127,
	
		/// <summary>
		/// 条款提示窗口
		/// </summary>
		Reminder = 500128,
	
		/// <summary>
		/// 传送带进度条
		/// </summary>
		ConveyorBar = 500129,
	
		/// <summary>
		/// 复习课侦测考题内容串场进度条
		/// </summary>
		ReviewSessionDetectsProcess = 500130,
	
		/// <summary>
		/// 通用UI特写(icon)
		/// </summary>
		CommonUICloseUpIcon = 500131,
	
		/// <summary>
		/// 打地鼠高级版
		/// </summary>
		PhonicsGopherSenior = 500132,
	
		/// <summary>
		/// 提示气泡界面
		/// </summary>
		BubbleTip = 500133,
	
		/// <summary>
		/// 实例列表容器
		/// </summary>
		InstanceContainer = 500135,
	
		/// <summary>
		/// 效果外化模板界面
		/// </summary>
		EffectExternalization = 500136,
	
		/// <summary>
		/// 历史课程列表界面
		/// </summary>
		HistoryLesson = 500137,
	
		/// <summary>
		/// 主页课程表子页面
		/// </summary>
		LessonCardContainer = 500139,
	
		/// <summary>
		/// 课程开始Afresh选择弹窗
		/// </summary>
		LessonAfreshPopwindow = 500142,
	
		/// <summary>
		/// 复习课
		/// </summary>
		LessonReview = 500146,
	
		/// <summary>
		/// 小游戏_翻卡片消除
		/// </summary>
		EliminateMiniGame = 500147,
	
		/// <summary>
		/// 本周课表界面
		/// </summary>
		WeekLesson = 500148,
	
		/// <summary>
		/// 小游戏_记忆卡片
		/// </summary>
		MemoryMiniGame = 500149,
	
		/// <summary>
		/// 小游戏_戳泡泡
		/// </summary>
		BalloonShooterMiniGame = 500150,
	
		/// <summary>
		/// 购买课程运营提示界面
		/// </summary>
		BuyLessonOperation = 500151,
	
		/// <summary>
		/// 小游戏_拼图
		/// </summary>
		PuzzleMiniGame = 500152,
	
		/// <summary>
		/// 小游戏_迷宫
		/// </summary>
		MazeMiniGame = 500153,
	
		/// <summary>
		/// 家长验证
		/// </summary>
		ParentConfirm = 500154,
	
		/// <summary>
		/// 老师介绍图片内容
		/// </summary>
		PictureAlone = 500155,
	
		/// <summary>
		/// 轻课登录UI
		/// </summary>
		LoginMobileUI_QK = 500156,
	
		/// <summary>
		/// 轻课游客UI
		/// </summary>
		Visitor_QK = 500157,
	
		/// <summary>
		/// 轻课课程展示UI
		/// </summary>
		ClassExhibition_QK = 500158,
	
		/// <summary>
		/// 轻客APP用户协议
		/// </summary>
		UserAgreement_QK = 500159,
	
		/// <summary>
		/// 轻客APP隐私条款
		/// </summary>
		UserPrivacy_QK = 500160,
	
		/// <summary>
		/// 轻客学生端个人信息
		/// </summary>
		QK_UserInfo = 500161,
	
		/// <summary>
		/// 轻客注销面板
		/// </summary>
		QK_UnRegister = 500162,
	
		/// <summary>
		/// 轻课主界面UI
		/// </summary>
		Home_QK = 500163,
	
		/// <summary>
		/// 轻课历史课程列表界面
		/// </summary>
		HistoryClass_QK = 500164,
	
		/// <summary>
		/// 轻客支付UI
		/// </summary>
		QK_Payment = 500165,
	
		/// <summary>
		/// 教师评价反馈
		/// </summary>
		TeacherFeedBack = 500166,
	
		/// <summary>
		/// Chant使用MP4播放的版本
		/// </summary>
		ChantVideo = 500167,
	
		/// <summary>
		/// 轻课权限页面手机端
		/// </summary>
		QK_AuthUIMobile = 500168,
	
		/// <summary>
		/// 课前等待页面（老师等待学生）
		/// </summary>
		ClassWaitStudent = 500169,
	
		/// <summary>
		/// 轻课条款提示窗口
		/// </summary>
		QK_Reminder = 500170,
	
		/// <summary>
		/// 轻课名称选择面板
		/// </summary>
		QK_NamePick = 500171,
	
		/// <summary>
		/// 轻客日期选择面板
		/// </summary>
		QK_PickerDate = 500172,
	
		/// <summary>
		/// 上课界面 提示
		/// </summary>
		TeacherPanelTips = 500173,
	
		/// <summary>
		/// 老师介绍图片内容
		/// </summary>
		CommonQA = 500174,
	
		/// <summary>
		/// 隐性语言综合练习-九宫格
		/// </summary>
		ComprehensiveLanPrac = 500175,
	
		/// <summary>
		/// 应用升级更新界面
		/// </summary>
		QK_AppUpdateUI = 500176,
	
		/// <summary>
		/// 家长验证
		/// </summary>
		QK_ParentConfirm = 500177,
	
		/// <summary>
		/// 直播效果外化模板界面
		/// </summary>
		LiveEffectExternalization = 500178,
	
		/// <summary>
		/// 登录信息补充-轻课
		/// </summary>
		InfoSupplement_QK = 500179,
	
		/// <summary>
		/// 选择面板-轻课
		/// </summary>
		Picker_QK = 500180,
	
		/// <summary>
		/// 放置游戏V2.0（直播）
		/// </summary>
		PlaceGameV2InLive = 500181,
	
		/// <summary>
		/// 直播_小游戏_翻卡片消除
		/// </summary>
		LiveEliminateMiniGame = 500182,
	
		/// <summary>
		/// 直播_记忆卡片通用
		/// </summary>
		LiveMemoryCard = 500183,
	
		/// <summary>
		/// 用户踢掉
		/// </summary>
		ForceQuit_QK = 500184,
	
		/// <summary>
		/// 左上角教学标题UI
		/// </summary>
		CommonInstanceTitle = 500185,
	
		/// <summary>
		/// 指令点击 显示道具列表(直播)
		/// </summary>
		CommandItemListInLive = 500186,
	
		/// <summary>
		/// 下方中央单词介绍UI
		/// </summary>
		IntroductionWords = 500187,
	
		/// <summary>
		/// 图片剪影UI
		/// </summary>
		IconSilhouette = 500188,
	
		/// <summary>
		/// sayhello   classroom rules_card
		/// </summary>
		SayHelloCard = 500189,
	
		/// <summary>
		/// 介绍颜色
		/// </summary>
		TrialIntroColor = 500190,
	
		/// <summary>
		/// 礼物飞出（新句式卡片）
		/// </summary>
		GiftFlyingOut = 500191,
	
		/// <summary>
		/// 总结 PPT
		/// </summary>
		SummaryPPT = 500192,
	
		/// <summary>
		/// 试听课直播句式练习
		/// </summary>
		TrialSentencePractice = 500193,
	
		/// <summary>
		/// 直播名词模板2.0
		/// </summary>
		NounColor = 500194,
	
		/// <summary>
		/// 名词形状教学
		/// </summary>
		NounShapeV2 = 500195,
	
		/// <summary>
		/// 主界面
		/// </summary>
		MainUIV2 = 500196,
	
		/// <summary>
		/// 直播-动词隐性教学-组合-2.0
		/// </summary>
		LiveVerbCombinationIconV2 = 500197,
	
		/// <summary>
		/// 串场进度条
		/// </summary>
		StageFieldProcessV2 = 500198,
	
		/// <summary>
		/// 综合应用-动形混合听音识意
		/// </summary>
		ComplexReviewV2 = 500199,
	
		/// <summary>
		/// 课程阶段选择界面
		/// </summary>
		LessonStage = 500200,
	
		/// <summary>
		/// UnityWebView通用界面
		/// </summary>
		UnityWebView = 500201,
	
		/// <summary>
		/// 拓展阅读主页面
		/// </summary>
		UIExpandReading_Main = 500202,
	
		/// <summary>
		/// 拓展阅读列表页面
		/// </summary>
		UIExpandReading_List = 500203,
	
		/// <summary>
		/// 拓展阅读视频播放页面
		/// </summary>
		UIExpandReading_Video = 500204,
	
		/// <summary>
		/// 拓展阅读绘本页面
		/// </summary>
		UIExpandReading_Book = 500205,
	
		/// <summary>
		/// 中英互译界面
		/// </summary>
		CETranslation = 500206,
	
		/// <summary>
		/// 课外辅导页面
		/// </summary>
		UITutor = 500207,
	
		/// <summary>
		/// 课中阶段
		/// </summary>
		Panel_ClassStep = 500208,
	
		/// <summary>
		/// 语音识别UI界面
		/// </summary>
		MainUIOutClass = 500209,
	
		/// <summary>
		/// 单词游戏
		/// </summary>
		WordGame = 500210,
	
		/// <summary>
		/// 串场地图
		/// </summary>
		ClassStepMap = 500211,
	
		/// <summary>
		/// 单词游戏-长颈鹿
		/// </summary>
		GiraffeGame = 500212,
	
		/// <summary>
		/// 单词游戏
		/// </summary>
		DragToFeedGame = 500213,
	
		/// <summary>
		/// 吹泡泡游戏
		/// </summary>
		BlowBubble = 500214,
	
		/// <summary>
		/// 单词游戏_三个动物
		/// </summary>
		ThreeAnimalGame = 500215,
	
		/// <summary>
		/// 单词游戏-冰激凌
		/// </summary>
		IceCreamGame = 500216,
	
		/// <summary>
		/// 角色扮演Timeline
		/// </summary>
		RoleCosplay = 500217,
	
		/// <summary>
		/// 单词游戏-狮子
		/// </summary>
		LionGame = 500218,
	
		/// <summary>
		/// 单词游戏
		/// </summary>
		DragToFeedCommandGame = 500219,
	
		/// <summary>
		/// 单词游戏
		/// </summary>
		ClickToFeedCommandGame = 500220,
	
		/// <summary>
		/// 课前准备关注公众号界面
		/// </summary>
		PreparationBeforeClass = 500221,
	
		/// <summary>
		/// 房间
		/// </summary>
		Room = 500222,
	
		/// <summary>
		/// 房间-换装
		/// </summary>
		Room_Clothes = 500223,
	
		/// <summary>
		/// 摘水果
		/// </summary>
		PickFruits = 500224,
	
		/// <summary>
		/// 字母卡片
		/// </summary>
		CCLetterCard = 500225,
	
		/// <summary>
		/// 单词游戏
		/// </summary>
		FishingGame = 500226,
	
		/// <summary>
		/// 跑跑卡丁车
		/// </summary>
		RunKartPanel = 500227,
	
		/// <summary>
		/// 情景应用13-选择工具完成任务（UI）
		/// </summary>
		ToolTask = 500228,
	
		/// <summary>
		/// 通用引导
		/// </summary>
		CCWidget = 500229,
	
		/// <summary>
		/// 情景应用18-装扮（UI）
		/// </summary>
		DressUp = 500230,



		/// <summary>
		/// Demo图片展示UI
		/// </summary>
		Demo_ShowPicture = 500500,

		/// <summary>
		/// Demo 激励送星
		/// </summary>
		Demo_ExcitationStar = 500501,

		/// <summary>
		/// Demo 汉字收集UI
		/// </summary>
		Demo_CharacterCollection = 500502,

		/// <summary>
		/// Demo 语音识别UI
		/// </summary>
		Demo_SpeechRecognition = 500503,

		/// <summary>
		/// Demo 气泡UI
		/// </summary>
		Demo_Bubble = 500504,

		/// <summary>
		/// Demo 暂停、退出UI
		/// </summary>
		Demo_PauseBack = 500505,

		/// <summary>
		/// Demo  月字收集游戏UI
		/// </summary>
		Demo_MoonGame = 500506,

		/// <summary>
		/// Demo  天字收集游戏UI
		/// </summary>
		Demo_SkyGame = 500507,

		/// <summary>
		/// Demo 汉字教学UI
		/// </summary>
		Demo_ChineseCharacterTeach = 500508,





		/// <summary>
		/// 选择题 3-1 到 3-3
		/// </summary>
		Exercise3Game = 500608,

	}
}
