namespace Edu100.Enum
{
	/// <summary>
	/// PanelAdapterType的枚举
	/// auto generated by T4
	/// </summary>
	public enum PanelAdapterType
	{
	
		/// <summary>
		/// 默认界面适配比例 （4:3）适用于 模板逻辑UI ，UI 需要在4:3环境下
		/// </summary>
		Default = 1,
	
		/// <summary>
		/// 全屏平铺(用于需要基于屏幕 进行拉伸的模块eg:客户端模块，弹框，主UI 等)
		/// </summary>
		FullScreen = 2,
	
	}
}
