name: Build Java Server

on:
  push:
    branches: [ main, master ]
    paths:
      - 'server/ra2server/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'server/ra2server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'corretto'
        
    - name: Grant execute permission for gradlew
      run: chmod +x server/ra2server/gradlew
      
    - name: Build with Gradle
      run: |
        cd server/ra2server
        ./gradlew build
        
    - name: Upload JAR artifacts
      uses: actions/upload-artifact@v4
      with:
        name: server-jar
        path: server/jar/